### ISSUE TITLE
url 등록 화면

### ISSUE THREAD

**Issue by IC-H** [IC-H/12th_OPEN_SW_DEV_CONF#19]
개인이 공지사항에 변경이 있을 시에 알림을 받을 수 있도록 url을 등록하는 화면, 기존에 시스템 내에 등록 되지 않을 경우에 추가하여 검색 가능하도록 한다.
url : {domain}/user/url/register/

**Comment by IC-H** [comment]
https://github.com/IC-H/12th_OPEN_SW_DEV_CONF/pull/35
https://github.com/IC-H/12th_OPEN_SW_DEV_CONF/pull/32
https://github.com/IC-H/12th_OPEN_SW_DEV_CONF/pull/31
상기의 PR에서 기능 구현

**Comment by miintto** [comment]
확인 완료
