### ISSUE TITLE
【백 엔드】【쉘】 vectorize

### ISSUE THREAD

**Issue by IC-H** [IC-H/12th_OPEN_SW_DEV_CONF#46]
# page의 HTML을 Vector화 시키는 기능 구현

## html_vector 구조
* url_id
  -domain_url.id
* lang_id 
 -lang_mst.id
* tag_id
 -tag.id
* tag_order 
 -html내 동일한 tag의 오름차순 순번
* word_id 
 -xx_word.id, xx는 lang_mst.language
* word_order
 -동일한 tag내의 문자의 오름차순 순번

각 url의 html을 상기의 구조로 벡터화 한다.

**Comment by IC-H** [comment]
#62

**Comment by miintto** [comment]
확인완료
