### ISSUE TITLE
【백 엔드】【쉘】한 URL에서 이동할 수 있는 URL 리스트 특정 하는 기능

### ISSUE THREAD

**Issue by IC-H** [IC-H/12th_OPEN_SW_DEV_CONF#49]
로직
1. URL의 Response로부터 HTML을 얻는다.
1. 받은 HTML로부터 Jquery를 제외한 JS파일을 다시 얻는다.
1. HTNL파일의 a, form태그로 부터 다음 URL 리스트 후보군을 얻는다.
1. JS파일로 부터 다음 URL의 리스트 후보군을 얻는다.

**Comment by IC-H** [comment]
#80

**Comment by miintto** [comment]
확인완료
